export type CourseDetail = {
  positioning: string;
  bestFor: string;
  avoidIf: string;
  teacherWork: string;
  studentKit: string[];
  teacherKit: string[];
  media: string[];
  extras: string[];
  availability: string;
  source?: string;
};

export const courseDetails: Record<string, CourseDetail> = {
  "super-minds": {
    positioning: "Живой детский курс, в котором язык соединён с историями, песнями, CLIL и развитием мышления. Он менее академичен, чем Academy Stars, но требует регулярной смены активности.",
    bestFor: "Активные младшие школьники, которым нужны сюжет, движение, творчество и равномерное развитие всех навыков.",
    avoidIf: "Ребёнку нужна прежде всего строгая отработка школьной грамматики или занятия проходят редко и без домашней практики.",
    teacherWork: "Средняя: готовый сценарий сильный, но игры, песни и проекты нужно организовать, а насыщенный урок — дозировать.",
    studentKit: ["Student’s Book / eBook", "Workbook с дополнительной практикой", "Digital Pack на Cambridge One"],
    teacherKit: ["Teacher’s Book с поурочными рекомендациями", "Presentation Plus / цифровая демонстрация", "Teacher Resources и материалы для контроля"],
    media: ["Аудио к заданиям, песням и историям", "Пять типов видео на юнит: истории, песни, грамматика и CLIL"],
    extras: ["Super Practice Book в ряде комплектаций", "Flashcards и дополнительные worksheets", "Онлайн-задания и тесты"],
    availability: "Точный цифровой пакет и срок доступа зависят от ISBN и рынка; проверяйте комплект конкретного уровня.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/primary/super-minds-2nd-edition",
  },
  "family-friends": {
    positioning: "Системный курс с быстрым темпом, сильной фонетикой, грамматикой и регулярным повторением. Особенно удачен, когда нужно подтянуть школьную программу, но заниматься по современному международному УМК.",
    bestFor: "Младшие школьники, которым важны понятная структура, опора для школьных оценок, чтение, письмо и прочная база.",
    avoidIf: "Ребёнку тяжело выдерживать быстрый темп и большое количество тренировки или основная цель — свободное спонтанное говорение.",
    teacherWork: "Низкая–средняя: курс хорошо организован и удобен для системной работы; разговорные выходы иногда стоит расширять своими заданиями.",
    studentKit: ["Class Book", "Workbook или Workbook with Online Practice", "Онлайн-практика и Student Resources в отдельных комплектах"],
    teacherKit: ["Teacher’s Book с поурочными заметками", "Classroom Presentation Tool", "Teacher’s Resource Pack / Teacher’s Site"],
    media: ["Class Audio и аудио к Workbook", "Видео и интерактивные материалы в цифровых комплектах", "Отдельная системная phonics-программа"],
    extras: ["Photocopy Masters и worksheets", "Fluency Time, тесты и progress checks", "Family and Friends Plus для расширения грамматики и лексики уровней 1–3"],
    availability: "На рынке есть несколько редакций и региональных комплектов. Не смешивайте Class Book одной редакции с Workbook другой.",
    source: "https://elt.oup.com/catalogue/items/global/young_learners/family_and_friends_second_edition/",
  },
  "kids-box": {
    positioning: "Разговорно-игровой курс для детей с большим количеством историй, песен, игр и заданий на взаимодействие. Книга даёт материал, но качество урока сильно зависит от подачи преподавателя.",
    bestFor: "Общительные дети, мини-группы и ученики, которым нужно начать говорить без ощущения академической нагрузки.",
    avoidIf: "Нужна плотная письменная или грамматическая программа либо преподаватель планирует просто идти по упражнениям без дополнительной отработки.",
    teacherWork: "Высокая: каждый урок желательно заранее собирать в понятный сценарий, продумывать смену заданий, реквизит, drilling и перенос языка в речь.",
    studentKit: ["Pupil’s Book / eBook", "Activity Book with Digital Pack", "Онлайн-практика на Cambridge One"],
    teacherKit: ["Teacher’s Book with Digital Pack", "Presentation Plus / eBook для показа", "Teacher Resources, тесты и дополнительная практика"],
    media: ["Class Audio, песни и чанты", "Анимации и видео в цифровом пакете", "Интерактивные игры и задания"],
    extras: ["Flashcards", "Постеры и дополнительные worksheets в зависимости от уровня", "Встроенная подготовка к Cambridge Young Learners"],
    availability: "В New Generation семь уровней; набор печатных приложений и Digital Pack зависит от выбранного ISBN.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/primary/kids-box-new-generation",
  },
  "academy-stars": {
    positioning: "Очень академичный и плотный детский курс: крупные тексты, системная грамматика, письмо, навыки работы с заданиями и постепенная экзаменационная подготовка.",
    bestFor: "Мотивированные школьники с хорошим темпом усвоения, которым нужна серьёзная база и переход к академическому английскому.",
    avoidIf: "У ребёнка слабая мотивация, медленное усвоение, трудности с чтением или мало времени на регулярную домашнюю работу.",
    teacherWork: "Средняя–высокая: методическая поддержка богатая, но тексты и языковой материал нужно дробить, проверять усвоение и адаптировать для слабых учеников.",
    studentKit: ["Pupil’s Book с Digital Pupil’s Book / App", "Workbook и Digital Workbook", "Навигационная практика на платформе Navio в совместимых комплектах"],
    teacherKit: ["Teacher’s Book / Teacher’s App", "Classroom Presentation Kit", "Test Generator, Resource Centre и Progress Tracker"],
    media: ["Class Audio", "Graphic Grammar animations", "Language in Use, speaking и culture/video materials — четыре типа видео"],
    extras: ["Grammar и skills worksheets", "Материалы для mixed ability", "Тесты, review units и проекты"],
    availability: "Состав цифрового доступа различается по стране и ISBN; название платформы также зависит от комплектации.",
    source: "https://www.macmillanenglish.com/us/catalogue/courses/young-learners/academy-stars-second-edition/course-information",
  },
  "gogetter": {
    positioning: "Доступный разговорный курс для младших подростков: тексты короче и проще, чем в Wider World, много диалогов, видео и повторения.",
    bestFor: "Ученики 10–14 лет, которым важно преодолеть страх речи, закрепить базу и без резкого скачка перейти к подростковым темам.",
    avoidIf: "Ученик любит сложные тексты, нуждается в академическом письме или уже уверенно работает выше B1.",
    teacherWork: "Средняя: структура понятная, но разговорные модели нужно доводить до свободной речи, а видео — использовать с заданиями до и после просмотра.",
    studentKit: ["Student’s Book", "Workbook", "eText / интерактивная практика в доступных цифровых комплектах"],
    teacherKit: ["Teacher’s Book", "Presentation Tool и teacher resources", "Тесты и материалы для контроля"],
    media: ["BBC video", "Class Audio", "Интерактивные задания и языковые модели"],
    extras: ["Photocopiable worksheets", "Дополнительная grammar/vocabulary practice", "Материалы MyEnglishLab / Pearson English Portal — по лицензии"],
    availability: "Цифровая платформа и набор ресурсов зависят от региона и даты выпуска кода доступа.",
    source: "https://www.pearson.com/languages/educators/connected-english-learning-program/secondary/gogetter.html",
  },
  "wider-world": {
    positioning: "Познавательный подростковый курс: длиннее и сложнее тексты, шире круг тем, больше культуры, CLIL и глобального контекста, чем в GoGetter.",
    bestFor: "Любознательные подростки с развитым кругозором, хорошим чтением и готовностью обсуждать реальные темы.",
    avoidIf: "Ученик быстро устаёт от текста, имеет слабую базу или нуждается прежде всего в простом разговорном старте.",
    teacherWork: "Средняя: поддержка хорошая, но сложные тексты, проекты и критическое мышление требуют scaffolding и предварительной работы с лексикой.",
    studentKit: ["Student’s Book / digital course", "Workbook", "Интерактивная практика на Pearson English Portal в совместимых пакетах"],
    teacherKit: ["Teacher’s Book", "Presentation Tool", "Teacher resources, assessment и материалы mixed ability"],
    media: ["BBC clips и интервью с реальными людьми", "Class Audio", "Видео и задания к CLIL-проектам"],
    extras: ["Worksheets", "Тесты и progress checks", "Проекты по global citizenship и sustainability"],
    availability: "Пять уровней Pre-A1–B1+; цифровые AI-функции доступны не во всех пакетах и регионах.",
    source: "https://www.pearson.com/languages/en-us/educators/connected-english-learning-program/secondary/wider-world.html",
  },
  "get-involved": {
    positioning: "Содержательный курс с выраженной проектной деятельностью: каждый юнит строится вокруг вопроса WDYT? — ученики исследуют реальную социальную тему, собирают необходимый язык и завершают работу совместным проектом. Параллельно развиваются критическое мышление, сотрудничество и аргументированная речь.",
    bestFor: "Сильные и мотивированные подростки, которые готовы обсуждать, исследовать и создавать совместные проекты.",
    avoidIf: "Ученик не любит открытые вопросы и проекты или пока нуждается в коротких, строго контролируемых заданиях.",
    teacherWork: "Средняя–высокая: готовых ресурсов много, но дискуссии, проекты и дифференциацию нужно модерировать, а не просто проверять по ключу.",
    studentKit: ["Student’s Book + Digital Student’s Book", "Workbook + Digital Workbook", "Student’s App и On-the-Go Practice"],
    teacherKit: ["Teacher’s Book / Teacher’s eBook", "Teacher’s App", "Classroom Presentation Kit, Test Generator и Progress Tracker"],
    media: ["Несколько жанров видео на юнит", "Course Audio", "Видео для critical thinking и project presentations"],
    extras: ["Итоговая проектная деятельность в каждом юните: исследование, обсуждение, подготовка и презентация результата", "Grammar Bootcamp, Reinforcement и Challenge activities", "Kahoot и Student’s Resource Centre"],
    availability: "Британская и American Edition имеют разные комплекты; проверяйте редакцию и уровень перед покупкой.",
    source: "https://www.macmillanenglish.com/us/catalogue/courses/teenagers/get-involved/course-information-1",
  },
  "life-vision": {
    positioning: "Плотный академичный курс для старших подростков: серьёзная лексика и грамматика, критическое мышление, навыки будущего и встроенная экзаменационная работа.",
    bestFor: "Ученики с долгосрочной целью B2–C1, международными экзаменами или дальнейшей учёбой на английском.",
    avoidIf: "Нужен лёгкий разговорный курс без большой домашней нагрузки или ученик пока не выдерживает академический темп.",
    teacherWork: "Средняя: готовая система assessment сильная, но уровень нужно диагностировать точно и выбирать, какие дополнительные блоки действительно нужны.",
    studentKit: ["Student Book with Online Practice / eBook", "Workbook with Online Practice", "Student Resources на Oxford English Hub"],
    teacherKit: ["Teacher’s Guide with Digital Pack", "Classroom Presentation Tool", "Teacher Resources и Assessment for Learning"],
    media: ["Class Audio и video-enhanced lessons", "Vision 360° / интерактивные визуальные материалы", "Видео по темам и навыкам"],
    extras: ["Tests и workbook review lessons", "Exam skills practice", "Дополнительные worksheets и professional development resources"],
    availability: "Цифровые компоненты и срок доступа зависят от конкретного ISBN; часть материалов размещена в Oxford English Hub.",
    source: "https://elt.oup.com/catalogue/items/global/teenagers/life-vision/",
  },
  "primary-path": {
    positioning: "Продвинутый literacy-курс для младшей школы на трёх опорах: чтение и письмо, oracy и творчество. В каждом юните есть Big Question и итоговый Big Challenge.",
    bestFor: "Сильные младшие школьники, билингвальные программы и дети, которым важно научиться читать, рассуждать и выступать на английском.",
    avoidIf: "У ребёнка слабая техника чтения, медленный темп и мало учебного времени: курс нельзя проходить поверхностно.",
    teacherWork: "Высокая: extended reading, dialogic reading, oracy и проекты требуют вопросов, моделирования речи, обратной связи и поэтапной подготовки.",
    studentKit: ["Student’s Book with eBook", "My Creative Journal и Oracy Cue Cards", "Activity Book with Digital Pack"],
    teacherKit: ["Teacher’s Edition with Digital Pack", "Presentation materials на Cambridge One", "Oracy Pack и методические видео"],
    media: ["Audio ко всем ключевым текстам", "Real-world video, Story Time и Grammar Time animations", "Oracy in Action videos"],
    extras: ["Grammar and Writing Workbook", "Flashcards", "STEAM Extension worksheets и Primary Reading Anthologies"],
    availability: "Во Second Edition уровни идут от Foundation до 6; часть приложений продаётся отдельно.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/primary/cambridge-primary-path-2nd-edition",
  },
  "prepare": {
    positioning: "Подростковый all-skills курс, который постепенно соединяет общий английский с форматом Cambridge Qualifications без превращения каждого урока в экзаменационный тренажёр.",
    bestFor: "Подростки, которым нужен долгий маршрут A1–C1 и мягкая подготовка к A2 Key, B1 Preliminary, B2 First или C1 Advanced.",
    avoidIf: "Нужна короткая интенсивная подготовка к конкретному экзамену или исключительно разговорный курс.",
    teacherWork: "Средняя: материалов много; важно отделять core lesson от необязательной экзаменационной практики и не перегружать слабого ученика.",
    studentKit: ["Student’s Book with eBook", "Workbook with Digital Pack", "Онлайн-практика на Cambridge One"],
    teacherKit: ["Teacher’s Book with Digital Pack", "Presentation Plus", "Teacher Resources и assessment"],
    media: ["Classroom Audio", "Видео по темам и культуре", "Аудио- и видеоматериалы цифрового пакета"],
    extras: ["Exam preparation sections", "Photocopiable worksheets", "Practice tests и progress tests"],
    availability: "Девять уровней; состав экзаменационной поддержки меняется по уровню и комплекту.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/secondary/prepare-2nd-edition",
  },
  "solutions": {
    positioning: "Структурированный академичный курс с сильным grammar–vocabulary ядром и подробной тренировкой чтения, письма и экзаменационных умений.",
    bestFor: "Подростки, которым нужна дисциплина, восполнение пробелов и системный рост школьной успеваемости.",
    avoidIf: "Ученик низкомотивирован, избегает письма и ожидает в основном игр и свободного общения.",
    teacherWork: "Низкая–средняя: уроки предсказуемы и хорошо обеспечены; для мотивации часто полезно добавлять живые speaking tasks и актуальные материалы.",
    studentKit: ["Student’s Book / eBook", "Workbook / Workbook eBook", "Online Practice в отдельных комплектах"],
    teacherKit: ["Teacher’s Book или Teacher’s Pack", "Teacher’s Resource Disk / цифровые ресурсы", "Classroom Presentation Tool в доступных пакетах"],
    media: ["Class Audio", "Видео в онлайн-компонентах", "Произносительная и listening practice"],
    extras: ["Photocopiable worksheets", "Unit tests, cumulative tests и skills tests", "Дополнительная grammar and vocabulary practice"],
    availability: "Third Edition имеет несколько региональных комплектов; цифровые сервисы и носители могут различаться.",
    source: "https://elt.oup.com/catalogue/items/global/teenagers/solutions_third_edition/",
  },
  "gateway": {
    positioning: "Интенсивный курс старшей школы с сильной грамматикой, лексикой, экзаменационной логикой и навыками для дальнейшей учёбы.",
    bestFor: "Амбициозные подростки, которым нужен маршрут A1+–C1, школьные экзамены и будущая академическая самостоятельность.",
    avoidIf: "Ученик младше целевой аудитории, слабо мотивирован или не готов к регулярной домашней работе.",
    teacherWork: "Средняя: Teacher’s App экономит подготовку, но насыщенный материал нужно приоритизировать под цель ученика.",
    studentKit: ["Student’s Book + Digital Student’s Book", "Workbook + Digital Workbook", "Student’s App и On-the-Go Practice"],
    teacherKit: ["Teacher’s Book / Digital Teacher’s Book", "Teacher’s App и Classroom Presentation Kit", "Homework Manager, Test Generator и Progress Tracker"],
    media: ["Встроенные audio и video", "Интерактивные self-marking activities", "Видео и материалы Virtual Classroom Exchange"],
    extras: ["CLIL, Culture и mixed-ability worksheets", "Kahoot", "Teacher’s Resource Centre"],
    availability: "Некоторые сервисы и Virtual Classroom Exchange зависят от рынка и действующей лицензии.",
    source: "https://www.macmillanenglish.com/us/catalogue/courses/teenagers/gateway-to-the-world/course-information",
  },
  "english-file": {
    positioning: "Разговорный взрослый курс с очень сильной системой произношения и формулой grammar–vocabulary–pronunciation, которая быстро выводит материал в речь.",
    bestFor: "Взрослые, которым нужны уверенность, бытовое общение, путешествия и заметный разговорный прогресс.",
    avoidIf: "Главная цель — академическое письмо, узкий ESP или конкретный экзамен.",
    teacherWork: "Низкая–средняя: сценарий урока удобный и мультимедиа встроено; важно не пропускать коммуникативные этапы ради выполнения всех упражнений.",
    studentKit: ["Student Book & Workbook multipack / eBook", "Skills Confidence", "Student Resources на Oxford English Hub"],
    teacherKit: ["Teacher’s Guide with Digital Pack", "Classroom Presentation Tool", "Teacher Resources, tests и photocopiables"],
    media: ["Class Audio", "Grammar, Vocabulary и Pronunciation videos", "Documentary, drama и skills video"],
    extras: ["Sound Bank и pronunciation practice", "Communicative worksheets", "Grammar, vocabulary и assessment materials"],
    availability: "Пятая редакция имеет разные multipack-комплекты и сроки цифрового доступа; проверяйте уровень и ISBN.",
    source: "https://elt.oup.com/catalogue/items/global/adult_courses/english-file-fifth-edition/",
  },
  "speakout": {
    positioning: "Медиа-насыщенный разговорный курс с аутентичной речью, BBC Studios и широким диапазоном акцентов. Хорошо развивает listening и уверенность в общении.",
    bestFor: "Взрослые и старшие подростки, которым нужен современный реальный английский для общения и путешествий.",
    avoidIf: "Ученик хочет медленную пошаговую грамматику или испытывает сильные трудности с аутентичным аудированием.",
    teacherWork: "Средняя: видео и speaking tasks требуют этапов pre-viewing, language focus и повторного выхода в речь.",
    studentKit: ["Student’s Book / eBook", "Workbook", "Online Practice в Pearson English Connect / совместимой платформе"],
    teacherKit: ["Teacher’s Book", "Presentation Tool", "Teacher resources, assessment и gradebook"],
    media: ["BBC Studios video", "Class Audio и множество акцентов", "Интерактивная listening/speaking practice"],
    extras: ["Photocopiable worksheets", "Tests", "Дополнительная grammar, vocabulary и pronunciation practice"],
    availability: "Название цифровой платформы и AI-инструменты зависят от приобретённого решения и региона.",
    source: "https://www.pearson.com/languages/educators/connected-english-learning-program/adult/speakout.html",
  },
  "empower": {
    positioning: "Спокойный сбалансированный курс с прозрачными целями уроков и встроенным измерением прогресса. Сильная сторона — понятная система обучения и assessment.",
    bestFor: "Взрослые, которым важны структура, регулярная обратная связь и равномерное развитие языка для жизни, работы или учёбы.",
    avoidIf: "Нужен ярко выраженный разговорный драйв, узкий профессиональный английский или экзаменационный интенсив.",
    teacherWork: "Низкая–средняя: курс легко планировать; преподавателю остаётся персонализировать темы и решить, сколько онлайн-оценивания использовать.",
    studentKit: ["Student’s Book with eBook", "Workbook / Digital Workbook", "Digital Pack на Cambridge One"],
    teacherKit: ["Teacher’s Book", "Presentation Plus", "Online Assessment и teacher resources"],
    media: ["Class Audio", "Documentary Video", "Audio и video внутри eBook"],
    extras: ["Unit progress tests", "Photocopiable activities", "Grammar, vocabulary и speaking practice"],
    availability: "Digital Pack обычно включает eBook, Digital Workbook и Online Assessment; проверяйте конкретный ISBN.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/adult-courses/empower-2nd-edition",
  },
  "roadmap": {
    positioning: "Гибкий взрослый курс с двойным маршрутом: короткое ядро speaking/key language или расширенный путь через чтение, письмо и аудирование.",
    bestFor: "Индивидуальные ученики и группы с разной продолжительностью курса, где преподавателю важно собирать персональный маршрут.",
    avoidIf: "Нужен полностью линейный учебник, который можно проходить страницу за страницей без методического выбора.",
    teacherWork: "Средняя–высокая: ресурсов много, но преподаватель должен осознанно выбрать основной и расширенный маршрут, иначе курс распадается на компоненты.",
    studentKit: ["Student’s Book / eText", "Workbook", "Online Practice / MyEnglishLab в совместимых пакетах"],
    teacherKit: ["Teacher’s Book", "Presentation Tool", "Teacher resources, Test Generator и gradebook"],
    media: ["Class Audio", "Видео и аутентичные speaking models", "Интерактивная практика"],
    extras: ["Рабочие листы для расширенного skills-маршрута", "Tests", "Дополнительные grammar и vocabulary activities"],
    availability: "Восемь уровней A1–C2; состав Pearson digital solution зависит от лицензии.",
    source: "https://www.pearson.com/languages/educators/connected-english-learning-program/adult/roadmap.html",
  },
  "business-partner": {
    positioning: "Модульный деловой курс: реальные рабочие ситуации, функциональный язык, Financial Times content, презентации, переговоры, переписка и employability skills.",
    bestFor: "Работающие взрослые, корпоративные группы и подготовка к международной профессиональной коммуникации.",
    avoidIf: "У ученика нет делового контекста или сначала требуется базовый General English.",
    teacherWork: "Средняя: уроки можно выбирать независимо, но кейсы нужно персонализировать под должность и отрасль ученика.",
    studentKit: ["Coursebook / eText", "Workbook в доступных комплектах", "Цифровая практика и дополнительные материалы"],
    teacherKit: ["Teacher’s Book", "Presentation Tool", "Teacher resources, tests и progress tracking"],
    media: ["Business video и интервью", "Class Audio", "Модели meetings, presentations и calls"],
    extras: ["Financial Times articles", "Business skills и employability worksheets", "MyEnglishLab / Pearson platform materials"],
    availability: "Coursebook работает автономно; объём цифрового дополнения зависит от приобретённого пакета.",
    source: "https://www.pearson.com/languages/en-us/educators/connected-english-learning-program/adult/business-partner.html",
  },
  "tourism": {
    positioning: "ESP-курс для индустрии туризма и hospitality: обслуживание гостей, бронирование, экскурсии, транспорт, гостиницы и профессиональная лексика.",
    bestFor: "Студенты профильных программ и сотрудники туризма, которым нужны типовые рабочие сценарии.",
    avoidIf: "Цель — обычные туристические поездки: профессиональная тематика будет лишней.",
    teacherWork: "Средняя: ролевые ситуации полезно адаптировать под реальную должность и обновлять устаревающие сервисные контексты.",
    studentKit: ["Coursebook", "Workbook", "Аудиокомпонент соответствующего уровня"],
    teacherKit: ["Teacher’s Book", "Методические материалы и keys", "Дополнительные тестовые материалы в отдельных пакетах"],
    media: ["Class Audio с профессиональными ситуациями", "Listening scenarios и role-play models"],
    extras: ["Case studies и role plays", "Vocabulary practice", "Профессиональные проекты"],
    availability: "Линейка архивная и заменяется Pearson Step Up; цифровые коды и старые платформы могут уже не поддерживаться.",
    source: "https://www.pearson.com/languages/educators/connected-english-learning-program/adult/step-up.html",
  },
  "mindset": {
    positioning: "Многоуровневый IELTS-курс от Cambridge: системно строит exam skills, академическую лексику и стратегии по четырём частям теста.",
    bestFor: "Кандидаты IELTS Academic с уровнем от A2 и понятной целевой оценкой; подходит для курса и управляемой самостоятельной работы.",
    avoidIf: "Общий английский существенно ниже требуемого уровня или нужен только IELTS General Training без адаптации материалов.",
    teacherWork: "Средняя: диагностика и feedback по Writing/Speaking обязательны; онлайн-модули не заменяют проверку продуктивных навыков.",
    studentKit: ["Student’s Book with Digital Pack", "Online modules", "Testbank / practice components в зависимости от редакции"],
    teacherKit: ["Teacher’s Book with Digital Pack", "Presentation materials", "Teacher resources и answer keys"],
    media: ["Exam listening audio", "Видео и модели speaking", "Интерактивная цифровая практика"],
    extras: ["Academic Study Skills modules", "Language-specific online modules в отдельных версиях", "Practice tests и progress checks"],
    availability: "Есть оригинальная версия и Updated Digital Pack; не смешивайте коды и книги разных выпусков.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/cambridge-english-exams-ielts/mindset-ielts-updated-digital-pack",
  },
  "complete-preliminary": {
    positioning: "Полноценный language-and-exam курс B1 Preliminary: не только варианты теста, но и развитие языка, типичные ошибки и пошаговые стратегии.",
    bestFor: "Подростки и взрослые на уровне около B1, которым нужна обстоятельная, а не экспресс-подготовка.",
    avoidIf: "Ученик ниже A2+ или готовится к ОГЭ: формат и критерии экзаменов различаются.",
    teacherWork: "Средняя: нужно чередовать обучение языку, отработку частей экзамена и полноценные mock tests.",
    studentKit: ["Student’s Book with/without answers", "Workbook with/without answers", "Online Practice / Digital Pack в соответствующих пакетах"],
    teacherKit: ["Teacher’s Book", "Presentation materials", "Answer keys и teacher resources"],
    media: ["Class Audio", "Workbook audio download", "Видео/цифровые материалы в Online Practice"],
    extras: ["Grammar и vocabulary reference", "Practice tests", "Exam Preparation Bank в отдельных редакциях"],
    availability: "Есть версии Preliminary и Preliminary for Schools; выбирайте вариант под возраст и экзамен.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/cambridge-english-exams-ielts/complete-preliminary-2nd-edition",
  },
  "compact-first": {
    positioning: "Короткий интенсив B2 First: высокая доля экзаменационных заданий, стратегии и точечная языковая работа без длинного общего курса.",
    bestFor: "Ученик с уверенным B1+/B2 и ограниченным сроком, которому нужен собранный экзаменационный маршрут.",
    avoidIf: "Нужно сначала поднять общий уровень или ученик плохо переносит высокий темп.",
    teacherWork: "Средняя–высокая: компактность требует строгого плана, регулярной проверки Writing/Speaking и дополнительной работы над индивидуальными пробелами.",
    studentKit: ["Student’s Book with/without answers", "Workbook with/without answers и audio", "Digital Pack в доступных комплектах"],
    teacherKit: ["Teacher’s Book", "Teacher resources", "Answer keys и дополнительные practice materials"],
    media: ["Class Audio", "Workbook audio", "Цифровая exam practice"],
    extras: ["Full wordlist", "Practice tests", "Grammar и vocabulary review"],
    availability: "Проверяйте, что покупается именно Third Edition и нужная версия — First или First for Schools.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/cambridge-english-exams-ielts/compact-first-3rd-edition",
  },
  "complete-advanced": {
    positioning: "Глубокий C1 Advanced course: развивает сложный язык параллельно с экзаменационными стратегиями, а не ограничивается тренировочными вариантами.",
    bestFor: "Сильные B2+/C1 ученики с достаточным временем на чтение, письмо, лексику и регулярную обратную связь.",
    avoidIf: "Уровень не достиг уверенного B2 или нужен очень короткий финальный марафон.",
    teacherWork: "Высокая: продуктивные задания требуют детальной проверки, а сложную лексику и Use of English — системного повторения.",
    studentKit: ["Student’s Book with Digital Pack", "Workbook with eBook", "Student’s Pack / Self-Study Pack"],
    teacherKit: ["Teacher’s Book with Digital Pack", "Teacher resources", "Answer keys и assessment materials"],
    media: ["Class Audio", "Аудио и видео цифрового пакета", "Exam listening practice"],
    extras: ["Wordlist", "Practice tests", "Grammar, vocabulary и exam skills bank"],
    availability: "Третья редакция имеет несколько наборов с ответами и без; состав Digital Pack зависит от ISBN.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/cambridge-english-exams-ielts/complete-advanced-3rd-edition",
  },
  "objective-proficiency": {
    positioning: "Сложный C2-курс в 20 компактных юнитах: насыщенная лексика, тонкие языковые различия, сложные темы и официальная подготовка к C2 Proficiency.",
    bestFor: "Очень сильные C1/C2 ученики, готовые много читать, писать и анализировать язык.",
    avoidIf: "Уровень ниже устойчивого C1 или нужна современная цифровая среда как основной инструмент.",
    teacherWork: "Высокая: требуется экспертная обратная связь, расширение тем, работа с register/collocation и актуальными образцами экзамена.",
    studentKit: ["Student’s Book with/without answers", "Workbook", "Student’s Book Pack / downloadable software в старых комплектах"],
    teacherKit: ["Teacher’s Book", "Presentation Plus DVD-ROM", "Answer keys и photocopiable practice"],
    media: ["Class Audio CDs / audio package", "Listening exam practice"],
    extras: ["Practice Test", "Vocabulary and language development", "Дополнительные актуальные official sample papers рекомендуется брать отдельно"],
    availability: "Это Second Edition с частью устаревших носителей; заранее проверяйте совместимость цифровых приложений.",
    source: "https://www.cambridge.org/cambridgeenglish/catalog/cambridge-english-exams-ielts/objective-proficiency-2nd-edition",
  },
  "oge-2026": {
    positioning: "Не УМК, а актуальный экзаменационный тренажёр: нужен для диагностики, тайминга и сборки полного формата ОГЭ.",
    bestFor: "Девятиклассники после изучения соответствующей грамматики, лексики и форматов заданий.",
    avoidIf: "Планируется использовать сборник вместо основного языкового курса или начинать подготовку без разбора навыков.",
    teacherWork: "Средняя: варианты нужно анализировать, классифицировать ошибки и возвращать ученика к языковым темам, а не только считать баллы.",
    studentKit: ["Печатный сборник типовых вариантов", "Ответы и критерии — согласно конкретному изданию"],
    teacherKit: ["Методические комментарии и критерии в составе конкретного сборника"],
    media: ["Аудио для раздела Listening — по QR-коду, ссылке или приложению издательства"],
    extras: ["Бланки и дополнительные материалы зависят от автора и ISBN", "Открытый банк ФИПИ следует использовать отдельно"],
    availability: "Проверяйте год, автора и ISBN: состав сборников с похожими названиями различается, а формат обновляется ежегодно.",
  },
  "ege-2026": {
    positioning: "Не УМК, а сборник полного экзаменационного формата ЕГЭ для диагностики, тайминга и серии пробных работ.",
    bestFor: "Ученики 10–11 классов, которые параллельно системно развивают язык и отдельно тренируют Writing и Speaking.",
    avoidIf: "Сборник должен заменить General English, лексику, грамматику и обучение продуктивным заданиям.",
    teacherWork: "Высокая: письменную и устную части нельзя эффективно готовить только по ключам — нужны критерии, образцы и индивидуальная обратная связь.",
    studentKit: ["Печатный сборник типовых вариантов", "Ответы, критерии и дополнительные материалы — по конкретному ISBN"],
    teacherKit: ["Методические комментарии и шкалы оценивания в составе выбранного издания"],
    media: ["Аудио для Listening по QR-коду, ссылке или приложению издательства"],
    extras: ["Бланки — если включены издателем", "Открытый банк ФИПИ и демоверсия текущего года используются отдельно"],
    availability: "Ежегодно проверяйте соответствие актуальной демоверсии и спецификации; одинаковое название не гарантирует одинаковый комплект.",
  },
};
